version: "3.8"
services:
  app:
    build: ./docker/phpfpm
    volumes:
      - ./:/app
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    expose:
      - 9000

  server:
    build: ./docker/nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./app:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
    depends_on:
      - app

  db:
    build: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/log:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=${TZ}
    ports:
      - "${DB_PORT}:3306"
